theme: minima
title: My awesome blog
author: bestofallhans
email: myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  My awesome blog is a GitHub learning lab project.

# social links
twitter_username: bestofallhans # DO NOT include the @ character, or else the build will fail!
github_username:  bestofallhans # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
